version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: phillipchenme_nginx
    image: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/data:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - foundry
  certbot:
    image: certbot/certbot
    container_name: phillipchenme_certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/logs:/var/log/letsencrypt
      - ./data/certbot/data:/var/www/certbot
  foundry:
    image: felddy/foundryvtt:release
    hostname: scrubby_foundry_host
    init: true
    volumes:
      - type: bind
        source: /home/phillip/foundry/foundry_data
        target: /data
    environment:
      - CONTAINER_VERBOSE=true
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_ROUTE_PREFIX=foundry
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json

